### ISSUE TITLE
Per user access

### ISSUE THREAD

**Issue by jgardiner68** [Sterc/mediamanager#10]
Hello

This looks interesting

Is there a way I can use Media Manager to give each user their own media storage (so that they can upload an image into a TV) and not be able to manage other users media?

James

**Comment by jgardiner68** [comment]
It looks like I could create a Media Source per user but with 60+ users, that is a lot of work.

Is there a way to add a suffix to the basePath so that user1 only sees /assets/profile/user1 and user2 only sees /assets/profile/user2 and so on?

**Comment by gpsietzema** [comment]
Looks like you figured it out @jgardiner68 :-) That's what we did in some cases.

The per-user idea is not something we have done yet... I guess you could do it and you're free to do so. It's just that we haven't done it and are not looking into trying that ;-)

**Comment by jgardiner68** [comment]
thanks for the confirmation :-)

Can I drive MM programmatically to set up whats needed per user?

**Comment by sdrenth** [comment]
@jgardiner68 I think that would require some modifications. Feel free to submit a PR with such a feature.
