### ISSUE TITLE
MODX3S: Small GUI issues

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#16]
The MODX Logo at the top left gets shrunk, and the 2nd level navigation items in the main MODX navigation are not clickable. There is a large gap between them.

![Screenshot 2021-07-01 at 10 14 28](https://user-images.githubusercontent.com/447453/124090495-31f2c080-da55-11eb-804b-458443aac536.png)

**Comment by Oetzie** [comment]
@sonicpunk bootstrap CSS conflicts with MODx CSS. I am trying to fix it.

**Comment by sonicpunk** [comment]
This works. Can be closed.
