### ISSUE TITLE
MODX3S: Uploading files result in error

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#19]
![Screenshot 2021-09-23 at 09 47 51](https://user-images.githubusercontent.com/447453/134471588-be1b586e-bea3-4e24-bcd8-cd4e8bc440ba.png)

**Comment by sonicpunk** [comment]
Backend showing this error when loading the media manager component

`[2021-09-23 09:49:16] (WARN @ /var/www/html/cms/core/components/mediamanager/controllers/home.class.php : 55) PHP notice: Undefined index: templatesPath
[2021-09-23 09:49:19] (WARN @ /var/www/html/cms/core/model/modx/processors/resource/getnodes.class.php : 471) PHP notice: Undefined variable: classKeyIcon`

**Comment by Oetzie** [comment]
@sonicpunk I can not reproduce this issue, what error does the AJAX request contain? 

PS I fixed the error of the error log.

**Comment by sonicpunk** [comment]
@Oetzie This gets solved when these changes take place:
https://github.com/Sterc/mediamanager/issues/17

**Comment by sonicpunk** [comment]
This could be closed.
