### ISSUE TITLE
MODX3S: Feature request: Metadata Template

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#21]
Our client would like to have a meta field that is a required field when adding an image. In this case it would be the source of the image. 

How could we extend the interface to allow for this feature? My idea would be to have the ability to add a metadata template. This template could  be a xml scheme or json or something something where we have the option of adding fields and also being able to have a field be required or not.

@gpsietzema to discuss today

**Comment by gpsietzema** [comment]
Plus: if you upload a file, the metafield should show up at that very moment:
![image](https://user-images.githubusercontent.com/381017/134504303-505b180e-4e13-4ea6-b6a5-a7df04fbb3e6.png)

**Comment by joeke** [comment]
@Oetzie When testing this and leaving a required field empty I get the following error message:

![Screenshot 2021-11-03 100010](https://user-images.githubusercontent.com/2332231/140032938-94cb7e9f-5e09-46a7-8f83-3b9034b598b5.png)

The [[+file]] placeholder is not set, and could you change the text to "File `[[+file]]` could not be saved. One or more of the required fields are not set, required fields are marked with an asterisk.".
Would also be nice if the required field inputs are highlighted with a red border, if that's not too much work :).

**Comment by sonicpunk** [comment]
What format should the json file have? And what is the setting name? Do we add the setting to the media source?

**Comment by Oetzie** [comment]
@sonicpunk you can add a property to the mediasource called `mediamanagerMeta`. This must be a valid JSON, for example: `[{"key":"author", "label":"Author", "required": true}, {"key":"photographer", "label":"Photographer"}]`

**Comment by sonicpunk** [comment]
Thanks!

**Comment by sonicpunk** [comment]
I just tested it locally and it seems to work!
