### ISSUE TITLE
After adding images to pages, no link reference getting shown in backend GUI

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#24]
I created an MM Image Content Block Field and inserted it into two pages each inside of their own MODX context. The image gets properly outputted in the frontend, but in the MM Backend, links to where the images are being used do not appear in the link list:

![Screenshot 2021-11-09 at 11 40 32](https://user-images.githubusercontent.com/447453/140909831-49e7016c-d826-4853-9338-6bf2f6510dff.png)

**Comment by sonicpunk** [comment]
In a multi-site setup, you may run into the pagetitles being identical. See here: Both home pages have the same pagetitle. Could we at least in parentheses add the Resource ID to differentiate?

![Screenshot 2021-11-23 at 09 31 53](https://user-images.githubusercontent.com/447453/142991818-a9ff10e3-8645-45e1-9c25-d721a66e2fd4.png)

**Comment by sonicpunk** [comment]
@gpsietzema This issue may be related to this:
https://github.com/Sterc/mediamanager/issues/35

It seems you need to save a MODX resource twice to get the changes in the database.

**Comment by ilyautkin** [comment]
@sonicpunk I think this should be fixed in `0.2.8` version. And we added resource ID in preview popup.

**Comment by sonicpunk** [comment]
@ilyautkin Nice! Works!
