### ISSUE TITLE
Archiving feature questions

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#25]
Does archiving only shift the image to the Archiving category?
What other functionality is affected by archiving? For example... if I archive an image, should it disappear in all instances where it is used in the frontend?

**Comment by ilyautkin** [comment]
@sonicpunk if you use image in the frontend (for example in ContentBlock field or in TV), button `Archive` will be `Archive & replace`. And you can replace image anywhere in frontend. In other case, image moves to archive directory and old links will return 404 error. They will work again if you unarchive file.

And last - in archive you can find button `Delete` - you can delete image, all versions and thumbnails from server by this button.

**Comment by sonicpunk** [comment]
Closing this. Thanks for the explanation.
