### ISSUE TITLE
Available sizes is not being populated with information

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#29]
When adding a new image, or cropping a new version of the image, this field stays empty.

What is it for? Does it not work?

![Screenshot 2021-11-09 at 12 19 40](https://user-images.githubusercontent.com/447453/140915035-ff14ea21-812e-41b2-9028-9e89ca1daa3c.png)

**Comment by Oetzie** [comment]
@sonicpunk I have tested this, and when you make a new crop and save it as a **new** image it works.

**Comment by joeke** [comment]
@sonicpunk As @Oetzie mentioned; this only seems to be available when saving as a new image. So maybe the label text should be clarified; Perhaps change it to `Other available sizes` or `Alternate sizes`? Or we could add a help-text on the right explaining what this does.

**Comment by sonicpunk** [comment]
I am also not sure what this information would be for. Unless there were direct links to open the alternative sizes or at least show the names of the linked images, not sure what value it has.

**Comment by sonicpunk** [comment]
This works. We can close it.
