### ISSUE TITLE
Can't seem to Delete Images

### ISSUE THREAD

**Issue by neoneddy** [Sterc/mediamanager#3]
Selected, but not delete option.  Tried right+clicking and  the delete button on keyboard.

**Comment by sdrenth** [comment]
@neoneddy Have you tried using the latest version?

**Comment by sonicpunk** [comment]
@neoneddy I can confirm that in the latest version it is working. I would suggesting closing this.

**Comment by neoneddy** [comment]
Sounds good.  Thanks everyone.
