### ISSUE TITLE
After upgrade to 0.2.5 HTTP instead of HTTPS being used - leads to Browser blocking calls.

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#30]
When testing the image cropping, we have a problem that the ajax request is not handling the call via HTTPs and the browser blocks it. The browser reports mixed content.

I also noticed that the Media Link in the GUI also is not using HTTPS:

![Screenshot 2021-11-23 at 09 15 34](https://user-images.githubusercontent.com/447453/142989827-18487c1d-a104-43d2-9428-23eb7cb30d91.png)

**Comment by sonicpunk** [comment]
![Uploading Screenshot 2021-11-23 at 09.16.26.png…]()

**Comment by sonicpunk** [comment]
![Screenshot 2021-11-23 at 09 16 26](https://user-images.githubusercontent.com/447453/142989981-41fd8de4-538f-4809-8dd7-a0ef9493d2b6.png)

**Comment by sonicpunk** [comment]
@gpsietzema It seems that in the files.class.php that you are referencing the MODX Option site_url. We have a Multisite Setup, and did not specifically assign site_url as a system setting. MODX was sending your script automatically a http request, instead of https. After adding the site_url explicitly to the CMS the error no longer exists. I think it may be then more of an issue with our testing environment.

**Comment by sonicpunk** [comment]
I think we can close this. @gpsietzema

**Comment by ilyautkin** [comment]
@sonicpunk yes, media manager used `site_url` in method `fileUrl` for creating full URL to file. By default MODX fill this setting by current host.
