### ISSUE TITLE
Archive and replace feature 

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#31]
I am not understanding this feature. It seems to not replace anything.

I click on "Archive & Replace" and there is no way to select an image to replace it with.

![Screenshot 2021-11-23 at 09 37 25](https://user-images.githubusercontent.com/447453/142992570-7c594905-6941-48df-a200-ae09b5909a19.png)

**Comment by sonicpunk** [comment]
This may be best if I do a show and tell via a Video Chat.

**Comment by sonicpunk** [comment]
When I select an image, it opens the image in a new window and shows the button "Archive & Replace" in red. 

In the MODX logs, I get an error that it cannot find the image

`[2021-11-23 09:58:29] (ERROR @ /var/www/html/cms/core/components/mediamanager/model/mediamanager/classes/files.class.php : 1409) PHP warning: getimagesize(/var/www/html/cms/2021/11/0529-stefan-deutsch.jpg): failed to open stream: No such file or directory`

**Comment by sonicpunk** [comment]
I see here that the path is not correct. The path is missing the container folder "media" in our case.

**Comment by sonicpunk** [comment]
Our Media Source is setup like this:

![Screenshot 2021-11-23 at 10 01 28](https://user-images.githubusercontent.com/447453/142995899-25ae40bf-a40e-4824-bcc7-81a0ba26c391.png)

**Comment by ilyautkin** [comment]
@sonicpunk Feature `Archive & Replace` used when image was linked to some resource. In this case you can select - what image will replace your archived image. This is demo: https://youtu.be/jqQ2O6euJgo

**Comment by sonicpunk** [comment]
@ilyautkin Does this work with Content Block MM Image fields?

**Comment by ilyautkin** [comment]
@sonicpunk Yes, it should replace ContentBlock fields too

**Comment by sonicpunk** [comment]
@ilyautkin I tested it out and in my case the url for the replaced image is not correct when showing it in the MODX form:

![Screenshot 2021-12-07 at 08 54 23](https://user-images.githubusercontent.com/447453/144988833-80b50759-8144-4e6e-8563-9d09394fe643.png)

**Comment by gpsietzema** [comment]
@ilyautkin can you have a look?
@sonicpunk can you share you mediasource settings.

**Comment by sonicpunk** [comment]
![Screenshot 2021-12-07 at 14 57 45](https://user-images.githubusercontent.com/447453/145042323-f6727cc8-dbd7-4ad4-9803-450518e59441.png)

**Comment by ilyautkin** [comment]
@sonicpunk, good morning! There is [new 0.2.7](https://modx.com/extras/package/mediamanagerbeta) version with fixes of `Archive & Replace` for TVs and ContentBlock fields.

**Comment by sonicpunk** [comment]
@ilyautkin I will check it out today and get back to you. Thanks!

**Comment by sonicpunk** [comment]
@ilyautkin are you only allowed to replace an image with another image that has not yet been used?

**Comment by sonicpunk** [comment]
@ilyautkin I just tested the following:

MODX resource uses photo A for a MODX TV AND a Content Block Media Manager Image Field.
1) uploaded new photo B
2) Clicked on photo A in the media manager and selected archive and replace
3) clicked on photo B
4) Refreshed the MODX resource using photo A

What I saw was that in the MODX TV photo A was correctly changed to photo B. But the Content Block Field did NOT change. Is the expected behaviour that content block fields are not getting replaced?

**Comment by ilyautkin** [comment]
@sonicpunk I checked this in `0.2.8` - https://youtu.be/poJV9vdeXm4
Now it should be fixed.

**Comment by sonicpunk** [comment]
@ilyautkin This is working now. Thank you so much!

**Comment by sonicpunk** [comment]
@ilyautkin What happens to an archived image in the website Frontend? Will it trigger a 404? Or does nothing happen and the image is still available in the frontend.

**Comment by sonicpunk** [comment]
@sdrenth What happens in the frontend and in the modx resources when an image gets archived? Does it not get removed or handled in some way?

**Comment by sdrenth** [comment]
@sonicpunk When archiving a file, the file is also physically being moved to a different folder (/archived/). In the frontend it will still output the original source path. So the frontend in this case will show a broken image.
