### ISSUE TITLE
When adding and deleting images from content - database changes do not seem to be getting saved

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#35]
I have been observing the database table "mediamanager_files_content" because I have been seeing that the media links are not working as expected.

![Screenshot 2021-12-13 at 13 31 07](https://user-images.githubusercontent.com/447453/145812719-2971e799-54d6-462a-b4d5-557d97472e7f.png)
![Screenshot 2021-12-13 at 13 31 35](https://user-images.githubusercontent.com/447453/145812747-bc2bf621-0de3-414b-a296-ae17c5659f68.png)

When I upload an image via Content Block Media Manager Image field and save the resource, it does not update this database table. When I save the resource a 2nd time it does.

**Comment by sonicpunk** [comment]
Also when I remove a Content Block Media Manager field, I need to save the MODX resource 2 times for the entry to be removed from the database.

**Comment by sonicpunk** [comment]
@ilyautkin Hope my description was ok!

**Comment by ilyautkin** [comment]
@sonicpunk hello! I checked `0.2.7` and database entries creating and deleting after first save. Here is video demo: https://youtu.be/eJ4CQuIL1lY

Maybe you did something else? How can I reproduce this bug? Maybe you can make video from screen?

**Comment by sonicpunk** [comment]
@ilyautkin One thing you should know, is that we are using MODX3S for the project and not 2x. This also led to this issue that was solved become again unresolved for MODX3S
https://github.com/Sterc/mediamanager/issues/15

**Comment by ilyautkin** [comment]
@sonicpunk fixed in `0.2.8` - https://github.com/Sterc/mediamanager/commit/0bd12d0306a135f378b5222f72c694727dcfc2ee#diff-2a44655479a1a428c31dcf923e0d6f23b43918e2c357cd6fbc48b19895c225a7R27

**Comment by sonicpunk** [comment]
@ilyautkin Thanks for the update. I will test out 0.2.8. I will also. make a video showing this error if it still exists for me.

**Comment by sonicpunk** [comment]
@ilyautkin I made a video showing the issue. MODX 3S. Sorry about the video quality.

https://youtu.be/P7sAHiTsjeI

**Comment by ilyautkin** [comment]
@sonicpunk I checked work on MODX 3S - and it's ok. What I think. This rows are deleting and creating by plugin on event `OnDocFormSave`. Maybe you have some other plugins on this event - and one of this plugin conflicted with `mediaManagerCustomTv`... Can you please check plugins or maybe send me access to manager to `ilya@heibel.nl`? I will check and fix if I can.

**Comment by sonicpunk** [comment]
@ilyautkin Ok, seems you are right. One of our plugins seems to have caused the issue. Closing!
