### ISSUE TITLE
V. 0.2.9 Content Blocks Image Gallery type not saving link in database

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#47]
When I use the Content Blocks Gallery for MediaManager input type and save an image to a Resource, the linked to field does not get populated

![Screenshot 2022-05-17 at 14 08 19](https://user-images.githubusercontent.com/447453/168807635-4c037f68-2466-45a3-b72f-3245b1d3fe7e.png)

**Comment by sonicpunk** [comment]
Did not test this on ver .0.3.0

**Comment by sdrenth** [comment]
@sonicpunk This is included in the v0.3.1 release.
