### ISSUE TITLE
Archiving and Replacing visual interface confusing.

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#50]
In our usability testing we have determined that the workflow for archiving and replacing images should be optimized.
When a user successfully replaces an image, the edit screen of that image gets shown but no success message is displayed. In the edit screen that gets shown, there still exists the Archive and Replace button (in red), which makes the user think that they still have to do something. 

We would suggest that after replacing the image a success message gets shown instead of the edit window.

**Comment by sdrenth** [comment]
@sonicpunk This is included in the v0.3.1 release.
