### ISSUE TITLE
ACLs - Mediasource and User Permissions

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#51]
Users that are not setup to see a certain mediasource in the Media Manager still can see the content of that mediasource inside of the MediaManager. They can't edit the files, but they still get the option in the dropdown.

Better would be if they can only access the mediasources that they have ACL permissions to. 

You know what I mean?

**Comment by sdrenth** [comment]
@sonicpunk This is included in the v0.3.1 release.
