### ISSUE TITLE
Metadata required fields validation message shows key instead of label value

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#52]
When testing the required meta fields, the error that gets shown uses the key instead of the label value. This is then confusing for the user.

**Comment by sdrenth** [comment]
@sonicpunk Could you add a screenshot of the error message please?

**Comment by sonicpunk** [comment]
![Screenshot 2022-07-27 at 16 34 45](https://user-images.githubusercontent.com/447453/181274796-88201edc-6172-4929-aaa6-60b488e0be24.png)

**Comment by sonicpunk** [comment]
And at the top of the page:

![Screenshot 2022-07-27 at 16 36 00](https://user-images.githubusercontent.com/447453/181275046-e5d19180-a91c-42be-9e66-b912e8fff538.png)

**Comment by sdrenth** [comment]
@sonicpunk This is included in the v0.3.1 release.
