### ISSUE TITLE
Sub Category management has UI issues

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#57]
When creating a subcategory, the visual interface on the categories editing page becomes not usable.
- Add a subcategory to a category and you will see the problem.

On the image edit views there is also a UI problem. Subcategories do not get listed in any kind of hierarchy and therefore if you have subcategories that have the same name, you will not be able to decide which subcategory to choose. It's parent is not visually shown.
- Try this in the image upload view AND in the image edit view.

MODX v3.0.1, MediaManager v0.3.1

**Comment by sonicpunk** [comment]
![Screenshot 2022-11-07 at 17 42 01](https://user-images.githubusercontent.com/447453/200509904-c53daf4e-5ef8-4939-b21e-7fe7b76e2e65.png)

**Comment by sonicpunk** [comment]
![Screenshot_2022-11-07_at_17_43_13_png](https://user-images.githubusercontent.com/447453/200510198-292a0415-c5d6-4ba0-82ff-ce1d0e309d1e.png)

**Comment by sonicpunk** [comment]
In devtools you see the following JS errors:

![Screenshot 2022-11-10 at 15 42 12](https://user-images.githubusercontent.com/447453/201121149-ab8a8b2c-7d22-4696-b050-b0a7d56ceb29.png)

**Comment by sonicpunk** [comment]
@gpsietzema Any progress here?

**Comment by joeke** [comment]
@sonicpunk I've pushed some fixes for this, the categories dropdown options are now prefixed with the parents list.  
![Screenshot 2022-12-09 at 11 11 47](https://user-images.githubusercontent.com/2332231/206680783-1321b19b-71c0-4a1f-af18-3d74a540e3d0.png)

However I can't seem to reproduce the behaviour and errors you mention in the Media Categories management. That seems to be working as expected on my test environment (MODX 3.0.1).
![Screenshot 2022-12-09 at 11 25 00](https://user-images.githubusercontent.com/2332231/206681094-8eaec671-c7cd-4e15-846e-a1f6f0d3a5b1.png)

Could you have a test with the latest transport zip to see if that solves it for you?
https://github.com/Sterc/mediamanager/blob/development/_packages/mediamanager-0.3.2-pl.transport.zip

**Comment by sonicpunk** [comment]
Thanks! It looks good now!
