### ISSUE TITLE
Source dropdown as required field

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#58]
Could you please see that this dropdown field is a required field? Thanks! @gpsietzema 

![Screenshot 2022-11-11 at 08 48 59](https://user-images.githubusercontent.com/447453/201292247-89ca496a-2c55-4279-b490-8ad9152df926.png)

**Comment by sonicpunk** [comment]
@gpsietzema Any progress here?

**Comment by joeke** [comment]
@sonicpunk Should be fixed now in latest transport zip. I've also added asterisks to the required license fields in the dropzone and edit forms to clarify which fields are required.
https://github.com/Sterc/mediamanager/blob/development/_packages/mediamanager-0.3.2-pl.transport.zip

**Comment by sonicpunk** [comment]
Thanks!
