### ISSUE TITLE
Loading Category Manager

### ISSUE THREAD

**Issue by temporalFluid** [Sterc/mediamanager#6]
On a fresh install of mediamanager 0.2.0-pl BETA from the package installer.  Running Mac OS with Firefox Quantum 59.02 (64) Here are the errors I receive:
`
unreachable code after return statement[Learn More]
modx.tree.js:763:16

window.controllers/Controllers is deprecated. Do not use it for UA detection.
ace.min.js:1:18511

TypeError: $.ui is undefined[Learn More]
jquery.nestedSortable.js:35:5
<anonymous>
http://www.mydomain.com/assets/components/mediamanager/libs/jquery-nested-sortable/2.0.0/js/jquery.nestedSortable.js:35:5
<anonymous>
http://www.mydomain.com/assets/components/mediamanager/libs/jquery-nested-sortable/2.0.0/js/jquery.nestedSortable.js:26:9
<anonymous>
http://www.mydomain.com/assets/components/mediamanager/libs/jquery-nested-sortable/2.0.0/js/jquery.nestedSortable.js:13:2

TypeError: $(...).nestedSortable is not a function[Learn More]
mediamanager-categories.js:31:13
sortable
http://www.mydomain.com/assets/components/mediamanager/js/mgr/mediamanager-categories.js:31:13
<anonymous>
http://www.mydomain.com/assets/components/mediamanager/js/mgr/mediamanager-categories.js:245:9
k
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:8:26070
fireWith
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:8:26892
ready
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:8:28749
h
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:7:21312

unreachable code after return statement[Learn More]
modx.tree.js:763:16
`

**Comment by temporalFluid** [comment]
When I click 'Edit' next to each listing, I get the error:

TypeError: $(...).html(...).append(...).dialog is not a function[Learn More]
mediamanager-categories.js:104:13
edit
http://www.mydomain.com/assets/components/mediamanager/js/mgr/mediamanager-categories.js:104:13
d
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:8:3280
dispatch
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:9:5804
add/q.handle
http://www.mydomain.com/assets/components/imageplus/js/mgr/imageplus.min.js:9:2512

**Comment by sdrenth** [comment]
@temporalFluid I cannot reproduce this error with latest version.
